extern const GeoLayout peter_geo[];
extern Lights1 peter_sm64_material_lights;
extern u8 peter_peter_grifin_ci8[];
extern u8 peter_peter_grifin_ci8_pal_rgba16[];
extern Vtx peter_Plane_mesh_vtx_0[4];
extern Gfx peter_Plane_mesh_tri_0[];
extern Gfx mat_peter_sm64_material[];
extern Gfx mat_revert_peter_sm64_material[];
extern Gfx peter_Plane_mesh[];
extern Gfx peter_material_revert_render_settings[];
